const T = new TextEncoder();
const SESSION_TTL = 14 * 86400;
const ITERATIONS = 210000;
const PRODUCT = "pocket-desktop";
const now = () => Math.floor(Date.now() / 1000);
const json = (value, status = 200, headers = {}) => new Response(JSON.stringify(value), {status, headers: {"content-type":"application/json; charset=utf-8","cache-control":"no-store",...headers}});
const fail = (code, message, status = 400) => json({error:{code,message}}, status);

function random(prefix = "") { const b = new Uint8Array(32); crypto.getRandomValues(b); return prefix + [...b].map(x => x.toString(16).padStart(2,"0")).join(""); }
function b64(bytes) { let s=""; for (const b of bytes) s += String.fromCharCode(b); return btoa(s); }
function unb64(value) { return Uint8Array.from(atob(value), c => c.charCodeAt(0)); }
async function sha(value) { const d = await crypto.subtle.digest("SHA-256", typeof value === "string" ? T.encode(value) : value); return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join(""); }
async function derive(password, salt, iterations = ITERATIONS) { const key = await crypto.subtle.importKey("raw", T.encode(password), "PBKDF2", false, ["deriveBits"]); return b64(new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations}, key, 256))); }
function equal(a,b) { const x=T.encode(String(a)),y=T.encode(String(b)); if(x.length!==y.length)return false; let d=0; for(let i=0;i<x.length;i++) d|=x[i]^y[i]; return d===0; }
function validEmail(v) { v=String(v||"").trim().toLowerCase(); if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)||v.length>254) throw new Error("Valid email required."); return v; }
function validPassword(v) { v=String(v||""); if(v.length<12||v.length>256) throw new Error("Password must contain 12–256 characters."); return v; }
function validLoginPassword(v) { v=String(v||""); if(!v||v.length>256) throw new Error("Password required."); return v; }
function validUsername(v) { v=String(v||"").trim().toLowerCase(); if(v.length<2||v.length>40||!/^[a-z0-9][a-z0-9_-]*$/.test(v)) throw new Error("Username: 2–40 letters, numbers, _ or -."); return v; }
async function payload(request) { if(!(request.headers.get("content-type")||"").includes("application/json")) throw new Error("JSON required."); const v=await request.json(); if(!v||typeof v!=="object"||Array.isArray(v)) throw new Error("JSON object required."); return v; }
function cookie(request,name) { for(const item of (request.headers.get("cookie")||"").split(";")){ const [k,...v]=item.trim().split("="); if(k===name)return decodeURIComponent(v.join("=")); } return ""; }
const sessionCookie = (value,maxAge=SESSION_TTL) => `pocket_session=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`;
const bearer = request => (request.headers.get("authorization")||"").replace(/^Bearer\s+/,"").trim();
const sameOrigin = request => !request.headers.get("origin") || request.headers.get("origin") === new URL(request.url).origin;

async function rate(env,key,max,windowSeconds){ const stamp=now(),windowStart=stamp-(stamp%windowSeconds); await env.DB.prepare(`INSERT INTO auth_limits(key,window_start,count) VALUES(?1,?2,1) ON CONFLICT(key) DO UPDATE SET window_start=CASE WHEN window_start=?2 THEN window_start ELSE ?2 END,count=CASE WHEN window_start=?2 THEN count+1 ELSE 1 END`).bind(key,windowStart).run(); const row=await env.DB.prepare("SELECT count FROM auth_limits WHERE key=?1").bind(key).first(); return Number(row?.count||0)<=max; }
async function current(request,env){ const raw=cookie(request,"pocket_session"); if(!raw)return null; const row=await env.DB.prepare(`SELECT s.id session_id,s.user_id,u.email,m.organization_id,m.role,o.name organization_name,o.plan FROM sessions s JOIN users u ON u.id=s.user_id JOIN memberships m ON m.user_id=u.id AND m.status='active' JOIN organizations o ON o.id=m.organization_id WHERE s.token_hash=?1 AND s.expires_at>?2 AND u.status='active' ORDER BY CASE m.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END LIMIT 1`).bind(await sha(raw),now()).first(); if(row)await env.DB.prepare("UPDATE sessions SET last_seen_at=?1 WHERE id=?2").bind(now(),row.session_id).run(); return row; }
async function requireUser(request,env,roles=null){ const user=await current(request,env); if(!user)return {response:fail("authentication_required","Sign in to continue.",401)}; if(roles&&!roles.includes(user.role))return {response:fail("forbidden","Organization role cannot perform this action.",403)}; return {user}; }
async function requireDevice(request,env){ const raw=bearer(request); if(!raw.startsWith("pk_device_"))return {response:fail("device_auth_required","Valid device credential required.",401)}; const device=await env.DB.prepare("SELECT * FROM devices WHERE secret_hash=?1 AND status='active'").bind(await sha(raw)).first(); return device?{device}:{response:fail("device_auth_required","Device credential is invalid or revoked.",401)}; }
async function isEntitled(env,org){ return env.DB.prepare("SELECT 1 ok FROM entitlements WHERE organization_id=?1 AND product=?2 AND status='active' AND (expires_at IS NULL OR expires_at>?3)").bind(org,PRODUCT,now()).first(); }
async function createUser(env,email,password){ const salt=new Uint8Array(18);crypto.getRandomValues(salt);const id="usr_"+crypto.randomUUID();await env.DB.prepare("INSERT INTO users(id,email,password_hash,password_salt,password_iterations,status,created_at) VALUES(?1,?2,?3,?4,?5,'active',?6)").bind(id,email,await derive(password,salt),b64(salt),ITERATIONS,now()).run();return id; }
async function issueSession(env,userId){ const raw=random("pk_session_"),stamp=now();await env.DB.prepare("INSERT INTO sessions(id,user_id,token_hash,expires_at,created_at,last_seen_at) VALUES(?1,?2,?3,?4,?5,?5)").bind("ses_"+crypto.randomUUID(),userId,await sha(raw),stamp+SESSION_TTL,stamp).run();return raw; }

async function bootstrap(request,env){ if(!sameOrigin(request))return fail("origin_denied","Cross-origin mutation denied.",403);const data=await payload(request);const count=await env.DB.prepare("SELECT COUNT(*) count FROM users").first();if(Number(count?.count||0)>0)return fail("already_bootstrapped","First organization already exists.",409);if(!env.BOOTSTRAP_TOKEN||!equal(data.bootstrap_token,env.BOOTSTRAP_TOKEN))return fail("invalid_bootstrap_token","Invalid bootstrap token.",403);const userId=await createUser(env,validEmail(data.email),validPassword(data.password)),orgId="org_"+crypto.randomUUID(),stamp=now(),name=String(data.organization_name||"POCKET Team").slice(0,80);await env.DB.batch([env.DB.prepare("INSERT INTO organizations(id,name,slug,plan,owner_user_id,created_at) VALUES(?1,?2,?3,'founder',?4,?5)").bind(orgId,name,"pocket-"+orgId.slice(-8),userId,stamp),env.DB.prepare("INSERT INTO memberships(organization_id,user_id,role,status,created_at) VALUES(?1,?2,'owner','active',?3)").bind(orgId,userId,stamp),env.DB.prepare("INSERT INTO entitlements(organization_id,product,status,source,created_at) VALUES(?1,?2,'active','bootstrap',?3)").bind(orgId,PRODUCT,stamp)]);return json({ok:true},201,{"set-cookie":sessionCookie(await issueSession(env,userId))}); }
async function login(request,env){ if(!sameOrigin(request))return fail("origin_denied","Cross-origin login denied.",403);const ip=request.headers.get("cf-connecting-ip")||"unknown";if(!await rate(env,"login:"+ip,12,300))return fail("rate_limited","Try again later.",429);const data=await payload(request);const ident=String(data.email||data.username||data.user||"").trim();if(!ident)return fail("bad_credentials","Enter your email or username.",400);const password=validLoginPassword(data.password);const user=ident.includes("@")?await env.DB.prepare("SELECT * FROM users WHERE email=?1 COLLATE NOCASE AND status='active'").bind(validEmail(ident)).first():await env.DB.prepare("SELECT * FROM users WHERE email=?1 COLLATE NOCASE AND status='active'").bind(ident.toLowerCase()).first();if(!user||!equal(await derive(password,unb64(user.password_salt),Number(user.password_iterations)),user.password_hash))return fail("bad_credentials","Email or password is incorrect. Sign up if you are new.",401);return json({ok:true},200,{"set-cookie":sessionCookie(await issueSession(env,user.id))}); }
async function logout(request,env){ const raw=cookie(request,"pocket_session");if(raw)await env.DB.prepare("DELETE FROM sessions WHERE token_hash=?1").bind(await sha(raw)).run();return json({ok:true},200,{"set-cookie":sessionCookie("",0)}); }
async function register(request,env){ if(!sameOrigin(request))return fail("origin_denied","Cross-origin registration denied.",403);const data=await payload(request),code=String(data.invite_code||data.invite||"").trim().toUpperCase();if(!code)return signup(request,env);const invite=await env.DB.prepare("SELECT * FROM invites WHERE code_hash=?1 AND uses<max_uses AND expires_at>?2").bind(await sha(code),now()).first();if(!invite)return fail("invalid_invite","Invite is invalid, expired, or exhausted.");const email=validEmail(data.email);if(invite.email&&invite.email.toLowerCase()!==email)return fail("invite_email_mismatch","Invite belongs to another email.",403);const userId=await createUser(env,email,validPassword(data.password));await env.DB.batch([env.DB.prepare("INSERT INTO memberships(organization_id,user_id,role,status,created_at) VALUES(?1,?2,?3,'active',?4)").bind(invite.organization_id,userId,invite.role,now()),env.DB.prepare("UPDATE invites SET uses=uses+1 WHERE id=?1 AND uses<max_uses").bind(invite.id)]);return json({ok:true},201,{"set-cookie":sessionCookie(await issueSession(env,userId))}); }
async function signup(request,env){ if(!sameOrigin(request))return fail("origin_denied","Cross-origin signup denied.",403);const ip=request.headers.get("cf-connecting-ip")||"unknown";if(!await rate(env,"signup:"+ip,6,3600))return fail("rate_limited","Too many signups. Try later.",429);const data=await payload(request),email=validEmail(data.email),password=validPassword(data.password),name=String(data.organization_name||data.display||"Personal").slice(0,80);const exists=await env.DB.prepare("SELECT 1 ok FROM users WHERE email=?1 COLLATE NOCASE").bind(email).first();if(exists)return fail("user_exists","That email already has an account. Sign in.",409);const userId=await createUser(env,email,password),orgId="org_"+crypto.randomUUID(),stamp=now();await env.DB.batch([env.DB.prepare("INSERT INTO organizations(id,name,slug,plan,owner_user_id,created_at) VALUES(?1,?2,?3,'public',?4,?5)").bind(orgId,name,"pocket-"+orgId.slice(-8),userId,stamp),env.DB.prepare("INSERT INTO memberships(organization_id,user_id,role,status,created_at) VALUES(?1,?2,'owner','active',?3)").bind(orgId,userId,stamp)]);return json({ok:true,signup:true,organization_id:orgId},201,{"set-cookie":sessionCookie(await issueSession(env,userId))}); }
async function me(request,env){ const a=await requireUser(request,env);if(a.response)return a.response;return json({ok:true,user:{id:a.user.user_id,email:a.user.email,role:a.user.role,organization:{id:a.user.organization_id,name:a.user.organization_name,plan:a.user.plan}},desktop_entitled:Boolean(await isEntitled(env,a.user.organization_id))}); }
async function organization(request,env){ const a=await requireUser(request,env);if(a.response)return a.response;const members=await env.DB.prepare("SELECT u.id,u.email,m.role,m.status,m.created_at FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.organization_id=?1 ORDER BY u.email").bind(a.user.organization_id).all();return json({organization:{id:a.user.organization_id,name:a.user.organization_name,plan:a.user.plan},members:members.results||[]}); }
async function invite(request,env){ const a=await requireUser(request,env,["owner","admin"]);if(a.response)return a.response;const data=await payload(request),code=random().slice(0,12).toUpperCase(),role=["admin","member","viewer"].includes(data.role)?data.role:"member";await env.DB.prepare("INSERT INTO invites(id,organization_id,code_hash,email,role,max_uses,uses,expires_at,created_by,created_at) VALUES(?1,?2,?3,?4,?5,?6,0,?7,?8,?9)").bind("inv_"+crypto.randomUUID(),a.user.organization_id,await sha(code),data.email?validEmail(data.email):null,role,Math.max(1,Math.min(Number(data.max_uses||1),50)),now()+Math.max(1,Math.min(Number(data.expires_days||14),90))*86400,a.user.user_id,now()).run();return json({ok:true,invite_code:code,role,note:"Shown once."},201); }
async function pairCode(request,env){ const a=await requireUser(request,env);if(a.response)return a.response;const code=random().slice(0,10).toUpperCase(),expires=now()+600;await env.DB.prepare("INSERT INTO pair_codes(id,organization_id,user_id,code_hash,expires_at,created_at) VALUES(?1,?2,?3,?4,?5,?6)").bind("pair_"+crypto.randomUUID(),a.user.organization_id,a.user.user_id,await sha(code),expires,now()).run();return json({ok:true,pair_code:code,expires_at:expires,cloud_url:new URL(request.url).origin}); }
async function pairDevice(request,env){ const data=await payload(request),code=String(data.pair_code||"").trim().toUpperCase(),pair=await env.DB.prepare("SELECT * FROM pair_codes WHERE code_hash=?1 AND used_at IS NULL AND expires_at>?2").bind(await sha(code),now()).first();if(!pair)return fail("invalid_pair_code","Pair code is invalid or expired.");const secret=random("pk_device_"),id="dev_"+crypto.randomUUID(),stamp=now(),name=String(data.name||"POCKET Desktop").slice(0,80);await env.DB.batch([env.DB.prepare("INSERT INTO devices(id,organization_id,user_id,name,platform,version,secret_hash,status,last_seen_at,created_at) VALUES(?1,?2,?3,?4,?5,?6,?7,'active',?8,?8)").bind(id,pair.organization_id,pair.user_id,name,String(data.platform||"unknown").slice(0,80),String(data.version||"").slice(0,30),await sha(secret),stamp),env.DB.prepare("UPDATE pair_codes SET used_at=?1 WHERE id=?2 AND used_at IS NULL").bind(stamp,pair.id)]);return json({ok:true,device:{id,name,status:"active"},device_secret:secret},201); }
async function heartbeat(request,env){ const a=await requireDevice(request,env);if(a.response)return a.response;const data=await payload(request);await env.DB.prepare("UPDATE devices SET last_seen_at=?1,version=?2 WHERE id=?3").bind(now(),String(data.version||a.device.version).slice(0,30),a.device.id).run();return json({ok:true,server_time:now()}); }
async function devices(request,env){ const a=await requireUser(request,env);if(a.response)return a.response;const rows=await env.DB.prepare("SELECT id,name,platform,version,status,last_seen_at,created_at FROM devices WHERE organization_id=?1 ORDER BY created_at DESC").bind(a.user.organization_id).all();return json({devices:rows.results||[]}); }
async function queueTask(request,env){ const a=await requireUser(request,env);if(a.response)return a.response;const data=await payload(request),device=await env.DB.prepare("SELECT id FROM devices WHERE id=?1 AND organization_id=?2 AND status='active'").bind(String(data.device_id||""),a.user.organization_id).first();if(!device)return fail("device_not_found","Select an active device.",404);const id="tsk_"+crypto.randomUUID(),kind=["chat","agent"].includes(data.kind)?data.kind:"chat",stamp=now(),input=data.input&&typeof data.input==="object"?data.input:{};await env.DB.prepare("INSERT INTO tasks(id,organization_id,user_id,device_id,kind,input_json,status,created_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,'queued',?7,?7)").bind(id,a.user.organization_id,a.user.user_id,device.id,kind,JSON.stringify(input),stamp).run();return json({ok:true,task:{id,kind,status:"queued"}},202); }
async function listTasks(request,env){ const a=await requireUser(request,env);if(a.response)return a.response;const rows=await env.DB.prepare("SELECT id,device_id,kind,status,result_json,error,created_at,updated_at FROM tasks WHERE organization_id=?1 ORDER BY created_at DESC LIMIT 100").bind(a.user.organization_id).all();return json({tasks:(rows.results||[]).map(row=>({...row,result:row.result_json?JSON.parse(row.result_json):null,result_json:undefined}))}); }
async function nextTask(request,env){ const a=await requireDevice(request,env);if(a.response)return a.response;const stamp=now();await env.DB.prepare("UPDATE tasks SET status='queued',lease_expires_at=NULL,updated_at=?1 WHERE device_id=?2 AND status='running' AND lease_expires_at<?1").bind(stamp,a.device.id).run();const row=await env.DB.prepare("SELECT * FROM tasks WHERE device_id=?1 AND status='queued' ORDER BY created_at LIMIT 1").bind(a.device.id).first();if(!row)return json({task:null});const lease=stamp+120,update=await env.DB.prepare("UPDATE tasks SET status='running',lease_expires_at=?1,updated_at=?2 WHERE id=?3 AND status='queued'").bind(lease,stamp,row.id).run();if(!update.meta?.changes)return json({task:null});return json({task:{id:row.id,device_id:row.device_id,kind:row.kind,input:JSON.parse(row.input_json),lease_expires_at:lease}}); }
async function completeTask(request,env,id){ const a=await requireDevice(request,env);if(a.response)return a.response;const data=await payload(request),status=data.ok?"completed":"failed",update=await env.DB.prepare("UPDATE tasks SET status=?1,result_json=?2,error=?3,lease_expires_at=NULL,updated_at=?4 WHERE id=?5 AND device_id=?6 AND status='running'").bind(status,data.ok?JSON.stringify(data.result??null):null,data.ok?null:String(data.error||"task failed").slice(0,2000),now(),id,a.device.id).run();return update.meta?.changes?json({ok:true,status}):fail("task_not_running","Task is not leased to this device.",409); }
async function downloads(request,env){ const a=await requireUser(request,env);if(a.response)return a.response;if(!await isEntitled(env,a.user.organization_id))return fail("desktop_entitlement_required","Desktop-download entitlement required.",403);const rows=await env.DB.prepare("SELECT id,version,arch,sha256,bytes,created_at FROM releases WHERE product=?1 AND status='published' ORDER BY created_at DESC").bind(PRODUCT).all();return json({releases:(rows.results||[]).map(row=>({...row,download_url:"/api/downloads/"+encodeURIComponent(row.id)}))}); }
async function download(request,env,id){ const a=await requireUser(request,env);if(a.response)return a.response;if(!await isEntitled(env,a.user.organization_id))return fail("desktop_entitlement_required","Desktop-download entitlement required.",403);const release=await env.DB.prepare("SELECT * FROM releases WHERE id=?1 AND product=?2 AND status='published'").bind(id,PRODUCT).first();if(!release)return fail("release_not_found","Desktop release not found.",404);const object=await env.DOWNLOADS.get(release.object_key);if(!object)return fail("release_object_missing","Release binary unavailable.",503);const headers=new Headers();object.writeHttpMetadata(headers);headers.set("etag",object.httpEtag);headers.set("cache-control","private, no-store");headers.set("content-disposition",`attachment; filename="POCKET-Desktop-${release.version}-${release.arch}.exe"`);headers.set("x-pocket-sha256",release.sha256);return new Response(object.body,{headers}); }
async function adminRelease(request,env){ if(!env.RELEASE_ADMIN_TOKEN||!equal(bearer(request),env.RELEASE_ADMIN_TOKEN))return fail("admin_token_required","Release administrator token required.",401);const data=await payload(request);for(const key of ["id","version","arch","object_key","sha256","bytes"])if(!data[key])return fail("missing_field",`Missing ${key}.`);await env.DB.prepare("INSERT INTO releases(id,product,version,arch,object_key,sha256,bytes,status,created_at) VALUES(?1,?2,?3,?4,?5,?6,?7,'published',?8) ON CONFLICT(id) DO UPDATE SET version=excluded.version,arch=excluded.arch,object_key=excluded.object_key,sha256=excluded.sha256,bytes=excluded.bytes,status='published',created_at=excluded.created_at").bind(String(data.id),PRODUCT,String(data.version),String(data.arch),String(data.object_key),String(data.sha256),Number(data.bytes),now()).run();return json({ok:true},201); }
async function adminEntitlement(request,env){ if(!env.RELEASE_ADMIN_TOKEN||!equal(bearer(request),env.RELEASE_ADMIN_TOKEN))return fail("admin_token_required","Release administrator token required.",401);const data=await payload(request),org=String(data.organization_id||"");if(!org)return fail("organization_required","organization_id required.");await env.DB.prepare("INSERT INTO entitlements(organization_id,product,status,source,expires_at,created_at) VALUES(?1,?2,'active',?3,?4,?5) ON CONFLICT(organization_id,product) DO UPDATE SET status='active',source=excluded.source,expires_at=excluded.expires_at").bind(org,PRODUCT,String(data.source||"operator"),data.expires_at?Number(data.expires_at):null,now()).run();return json({ok:true}); }

async function api(request,env){ const url=new URL(request.url),path=url.pathname,method=request.method;try{
  if(path==="/api/health"&&method==="GET"){const row=await env.DB.prepare("SELECT COUNT(*) users FROM users").first();return json({ok:true,service:"pocket-cloud",version:"1.0.0",users:Number(row?.users||0),runtime:"cloudflare-worker-d1-r2"});}
  if(path==="/api/bootstrap"&&method==="POST")return bootstrap(request,env);
  if(path==="/api/login"&&method==="POST")return login(request,env);
  if(path==="/api/logout"&&method==="POST")return logout(request,env);
  if(path==="/api/register"&&method==="POST")return register(request,env);
  if(path==="/api/signup"&&method==="POST")return signup(request,env);
  if(path==="/api/me"&&method==="GET")return me(request,env);
  if(path==="/api/organization"&&method==="GET")return organization(request,env);
  if(path==="/api/invites"&&method==="POST")return invite(request,env);
  if(path==="/api/devices/pair-code"&&method==="POST")return pairCode(request,env);
  if(path==="/api/devices/pair"&&method==="POST")return pairDevice(request,env);
  if(path==="/api/devices/heartbeat"&&method==="POST")return heartbeat(request,env);
  if(path==="/api/devices"&&method==="GET")return devices(request,env);
  if(path==="/api/tasks"&&method==="POST")return queueTask(request,env);
  if(path==="/api/tasks"&&method==="GET")return listTasks(request,env);
  if(path==="/api/device/tasks/next"&&method==="GET")return nextTask(request,env);
  let match=path.match(/^\/api\/device\/tasks\/([^/]+)\/complete$/);if(match&&method==="POST")return completeTask(request,env,decodeURIComponent(match[1]));
  if(path==="/api/downloads"&&method==="GET")return downloads(request,env);
  match=path.match(/^\/api\/downloads\/([^/]+)$/);if(match&&method==="GET")return download(request,env,decodeURIComponent(match[1]));
  if(path==="/api/admin/releases"&&method==="POST")return adminRelease(request,env);
  if(path==="/api/admin/entitlements"&&method==="POST")return adminEntitlement(request,env);
  return fail("not_found","API route not found.",404);
}catch(error){console.error(error);return fail("invalid_request",String(error.message||error).slice(0,500),400);}}

export default { async fetch(request,env){ const path=new URL(request.url).pathname; if(path.startsWith("/api/"))return api(request,env); if(["/","/desk","/get","/login","/register","/signup","/sign-up"].includes(path))return env.ASSETS.fetch(new Request(new URL("/index.html",request.url),request)); return env.ASSETS.fetch(request); } };
export {derive as passwordHash,sha as sha256,equal as safeEqual};
