"""POCKET integrations catalog — Claude-style connector list for the desk.

Each integration is a first-class entry agents and the Working board can use.
OpenTable is a first-class dining/reservation connector.

Execute path: pocket.integrations_exec.execute(id) — every entry is executable
via desktop app, signed-in Edge, working board, agent, or host tab.
"""

from __future__ import annotations

from typing import Any, Dict, List

# 54 integrations — id, name, category, blurb, action, url, desktop_app (optional)
# action: open | reserve | buy | research | notify | schedule | errand | analysis
#         | agent | remote | screen | tab | working
INTEGRATIONS: List[Dict[str, Any]] = [
    # AI
    {
        "id": "muse_spark",
        "name": "Muse Spark",
        "category": "AI",
        "icon": "✦",
        "blurb": "Meta multimodal reasoning · parallel lanes · meta.ai",
        "action": "agent",
        "agent": "muse_spark",
        "url": "https://www.meta.ai/",
        "prompt": "",
        "featured": True,
        "executable": True,
    },
    {
        "id": "chatgpt",
        "name": "ChatGPT",
        "category": "AI",
        "icon": "◎",
        "blurb": "OpenAI chat — desktop app or web",
        "action": "open",
        "url": "https://chatgpt.com",
        "desktop_app": "chatgpt",
        "prefer": "desktop",
        "prompt": "ChatGPT: ",
        "executable": True,
    },
    {
        "id": "copilot",
        "name": "Microsoft Copilot",
        "category": "AI",
        "icon": "✦",
        "blurb": "Windows Copilot host app",
        "action": "open",
        "url": "https://copilot.microsoft.com",
        "desktop_app": "copilot",
        "prefer": "desktop",
        "prompt": "Copilot: ",
        "executable": True,
        "featured": True,
    },
    # Dining / local
    {
        "id": "opentable",
        "name": "OpenTable",
        "category": "Dining",
        "icon": "🍽",
        "blurb": "Find tables, drive reservations (party · time · confirm with you)",
        "action": "reserve",
        "url": "https://www.opentable.com",
        "prompt": "Make a restaurant reservation via OpenTable: ",
        "featured": True,
        "executable": True,
    },
    {
        "id": "resy",
        "name": "Resy",
        "category": "Dining",
        "icon": "🥂",
        "blurb": "Hot restaurant bookings and waitlists",
        "action": "reserve",
        "url": "https://resy.com",
        "prompt": "Book a table on Resy: ",
        "executable": True,
    },
    {
        "id": "yelp",
        "name": "Yelp",
        "category": "Dining",
        "icon": "⭐",
        "blurb": "Reviews, hours, phone for venues",
        "action": "research",
        "url": "https://www.yelp.com",
        "prompt": "Research restaurants on Yelp: ",
        "executable": True,
    },
    {
        "id": "google_maps",
        "name": "Google Maps",
        "category": "Dining",
        "icon": "📍",
        "blurb": "Places, directions, hours",
        "action": "open",
        "url": "https://www.google.com/maps",
        "prompt": "Look up on Google Maps: ",
        "executable": True,
    },
    {
        "id": "doordash",
        "name": "DoorDash",
        "category": "Dining",
        "icon": "🛵",
        "blurb": "Delivery options research (you confirm order)",
        "action": "research",
        "url": "https://www.doordash.com",
        "prompt": "Find delivery options on DoorDash: ",
        "executable": True,
    },
    # Productivity
    {
        "id": "gmail",
        "name": "Gmail",
        "category": "Productivity",
        "icon": "✉️",
        "blurb": "Draft and open mail (you send)",
        "action": "notify",
        "url": "https://mail.google.com",
        "prompt": "Draft an email: ",
        "executable": True,
    },
    {
        "id": "outlook",
        "name": "Outlook",
        "category": "Productivity",
        "icon": "📬",
        "blurb": "Microsoft mail and calendar — desktop + web",
        "action": "notify",
        "url": "https://outlook.live.com",
        "desktop_app": "outlook",
        "prefer": "desktop",
        "prompt": "Draft Outlook message: ",
        "executable": True,
    },
    {
        "id": "google_calendar",
        "name": "Google Calendar",
        "category": "Productivity",
        "icon": "📅",
        "blurb": "Schedule drafts — you confirm",
        "action": "schedule",
        "url": "https://calendar.google.com",
        "prompt": "Schedule on Google Calendar: ",
        "executable": True,
    },
    {
        "id": "notion",
        "name": "Notion",
        "category": "Productivity",
        "icon": "📓",
        "blurb": "Docs and workspace notes — desktop or web",
        "action": "open",
        "url": "https://www.notion.so",
        "desktop_app": "notion",
        "prefer": "desktop",
        "prompt": "Work in Notion: ",
        "executable": True,
    },
    {
        "id": "slack",
        "name": "Slack",
        "category": "Productivity",
        "icon": "💬",
        "blurb": "Team chat — desktop app or web drafts",
        "action": "notify",
        "url": "https://app.slack.com",
        "desktop_app": "slack",
        "prefer": "desktop",
        "prompt": "Draft a Slack message: ",
        "executable": True,
    },
    {
        "id": "discord",
        "name": "Discord",
        "category": "Productivity",
        "icon": "🎮",
        "blurb": "Launch Discord desktop · community & team spaces",
        "action": "open",
        "url": "https://discord.com/app",
        "desktop_app": "discord",
        "prefer": "desktop",
        "prompt": "Discord: ",
        "featured": True,
        "executable": True,
    },
    {
        "id": "todoist",
        "name": "Todoist",
        "category": "Productivity",
        "icon": "✅",
        "blurb": "Tasks and errands on the board",
        "action": "errand",
        "url": "https://todoist.com",
        "prompt": "Add tasks: ",
        "executable": True,
    },
    {
        "id": "telegram",
        "name": "Telegram",
        "category": "Productivity",
        "icon": "✈",
        "blurb": "Telegram desktop messenger",
        "action": "open",
        "url": "https://web.telegram.org",
        "desktop_app": "telegram",
        "prefer": "desktop",
        "prompt": "Telegram: ",
        "executable": True,
    },
    # Dev
    {
        "id": "linear",
        "name": "Linear",
        "category": "Dev",
        "icon": "📐",
        "blurb": "Issues and product work",
        "action": "open",
        "url": "https://linear.app",
        "desktop_app": "linear",
        "prefer": "auto",
        "prompt": "Linear issues: ",
        "executable": True,
    },
    {
        "id": "jira",
        "name": "Jira",
        "category": "Dev",
        "icon": "🗂",
        "blurb": "Tickets and sprints",
        "action": "open",
        "url": "https://www.atlassian.com/software/jira",
        "prompt": "Jira work: ",
        "executable": True,
    },
    {
        "id": "github",
        "name": "GitHub",
        "category": "Dev",
        "icon": "🐙",
        "blurb": "Repos, PRs, issues via gh + GitHub Desktop",
        "action": "agent",
        "agent": "github",
        "url": "https://github.com",
        "desktop_app": "github",
        "prompt": "GitHub: ",
        "featured": True,
        "executable": True,
    },
    {
        "id": "gitlab",
        "name": "GitLab",
        "category": "Dev",
        "icon": "🦊",
        "blurb": "Repos and CI",
        "action": "open",
        "url": "https://gitlab.com",
        "prompt": "GitLab: ",
        "executable": True,
    },
    # Cloud
    {
        "id": "vercel",
        "name": "Vercel",
        "category": "Cloud",
        "icon": "▲",
        "blurb": "Deploy frontends",
        "action": "open",
        "url": "https://vercel.com",
        "prompt": "Deploy on Vercel: ",
        "executable": True,
    },
    {
        "id": "cloudflare",
        "name": "Cloudflare",
        "category": "Cloud",
        "icon": "☁",
        "blurb": "Workers, tunnels, DNS",
        "action": "open",
        "url": "https://dash.cloudflare.com",
        "prompt": "Cloudflare: ",
        "featured": True,
        "executable": True,
    },
    {
        "id": "aws",
        "name": "AWS Console",
        "category": "Cloud",
        "icon": "🟧",
        "blurb": "Amazon cloud console",
        "action": "open",
        "url": "https://console.aws.amazon.com",
        "prompt": "AWS: ",
        "executable": True,
    },
    {
        "id": "azure",
        "name": "Azure",
        "category": "Cloud",
        "icon": "🔷",
        "blurb": "Microsoft cloud",
        "action": "open",
        "url": "https://portal.azure.com",
        "prompt": "Azure: ",
        "executable": True,
    },
    {
        "id": "gcp",
        "name": "Google Cloud",
        "category": "Cloud",
        "icon": "🌈",
        "blurb": "GCP console",
        "action": "open",
        "url": "https://console.cloud.google.com",
        "prompt": "GCP: ",
        "executable": True,
    },
    # Commerce
    {
        "id": "stripe",
        "name": "Stripe",
        "category": "Commerce",
        "icon": "💳",
        "blurb": "Payments dashboard (you confirm charges)",
        "action": "open",
        "url": "https://dashboard.stripe.com",
        "prompt": "Stripe: ",
        "executable": True,
    },
    {
        "id": "shopify",
        "name": "Shopify",
        "category": "Commerce",
        "icon": "🛍",
        "blurb": "Store admin",
        "action": "open",
        "url": "https://www.shopify.com",
        "prompt": "Shopify: ",
        "executable": True,
    },
    {
        "id": "amazon",
        "name": "Amazon",
        "category": "Commerce",
        "icon": "📦",
        "blurb": "Buy research — you pay",
        "action": "buy",
        "url": "https://www.amazon.com",
        "prompt": "Buy on Amazon: ",
        "featured": True,
        "executable": True,
    },
    {
        "id": "ebay",
        "name": "eBay",
        "category": "Commerce",
        "icon": "🏷️",
        "blurb": "Listings and deals",
        "action": "buy",
        "url": "https://www.ebay.com",
        "prompt": "Find on eBay: ",
        "executable": True,
    },
    {
        "id": "ebay_motors",
        "name": "eBay Motors",
        "category": "Commerce",
        "icon": "🚗",
        "blurb": "Vehicles and parts",
        "action": "research",
        "url": "https://www.ebay.com/motors",
        "prompt": "Research eBay Motors: ",
        "executable": True,
    },
    # Social
    {
        "id": "linkedin",
        "name": "LinkedIn",
        "category": "Social",
        "icon": "💼",
        "blurb": "Profiles and outreach drafts",
        "action": "open",
        "url": "https://www.linkedin.com",
        "prompt": "LinkedIn: ",
        "executable": True,
    },
    {
        "id": "x_twitter",
        "name": "X (Twitter)",
        "category": "Social",
        "icon": "𝕏",
        "blurb": "Posts and research",
        "action": "open",
        "url": "https://x.com",
        "prompt": "On X: ",
        "executable": True,
    },
    {
        "id": "reddit",
        "name": "Reddit",
        "category": "Social",
        "icon": "🤖",
        "blurb": "Threads and research",
        "action": "research",
        "url": "https://www.reddit.com",
        "prompt": "Research on Reddit: ",
        "executable": True,
    },
    # Media
    {
        "id": "youtube",
        "name": "YouTube",
        "category": "Media",
        "icon": "▶",
        "blurb": "Videos and transcripts research",
        "action": "open",
        "url": "https://www.youtube.com",
        "prompt": "YouTube: ",
        "executable": True,
    },
    {
        "id": "spotify",
        "name": "Spotify",
        "category": "Media",
        "icon": "🎵",
        "blurb": "Music and podcasts — desktop or web",
        "action": "open",
        "url": "https://open.spotify.com",
        "desktop_app": "spotify",
        "prefer": "desktop",
        "prompt": "Spotify: ",
        "executable": True,
    },
    # Design
    {
        "id": "figma",
        "name": "Figma",
        "category": "Design",
        "icon": "🎨",
        "blurb": "Design files — desktop or web",
        "action": "open",
        "url": "https://www.figma.com",
        "desktop_app": "figma",
        "prefer": "desktop",
        "prompt": "Figma: ",
        "executable": True,
    },
    {
        "id": "canva",
        "name": "Canva",
        "category": "Design",
        "icon": "🖼",
        "blurb": "Quick visuals",
        "action": "open",
        "url": "https://www.canva.com",
        "prompt": "Canva: ",
        "executable": True,
    },
    # Files
    {
        "id": "dropbox",
        "name": "Dropbox",
        "category": "Files",
        "icon": "📂",
        "blurb": "Cloud files",
        "action": "open",
        "url": "https://www.dropbox.com",
        "prompt": "Dropbox: ",
        "executable": True,
    },
    {
        "id": "gdrive",
        "name": "Google Drive",
        "category": "Files",
        "icon": "💾",
        "blurb": "Docs and drive",
        "action": "open",
        "url": "https://drive.google.com",
        "prompt": "Google Drive: ",
        "executable": True,
    },
    {
        "id": "onedrive",
        "name": "OneDrive",
        "category": "Files",
        "icon": "☁",
        "blurb": "Microsoft files",
        "action": "open",
        "url": "https://onedrive.live.com",
        "prompt": "OneDrive: ",
        "executable": True,
    },
    {
        "id": "obsidian",
        "name": "Obsidian",
        "category": "Files",
        "icon": "◆",
        "blurb": "Local markdown vault — desktop app",
        "action": "open",
        "url": "https://obsidian.md",
        "desktop_app": "obsidian",
        "prefer": "desktop",
        "prompt": "Obsidian: ",
        "executable": True,
    },
    # Meetings
    {
        "id": "zoom",
        "name": "Zoom",
        "category": "Meetings",
        "icon": "📹",
        "blurb": "Meetings — desktop app or web",
        "action": "open",
        "url": "https://zoom.us",
        "desktop_app": "zoom",
        "prefer": "desktop",
        "prompt": "Zoom meeting: ",
        "executable": True,
    },
    {
        "id": "teams",
        "name": "Microsoft Teams",
        "category": "Meetings",
        "icon": "👥",
        "blurb": "Teams chat and calls — desktop first",
        "action": "open",
        "url": "https://teams.microsoft.com",
        "desktop_app": "teams",
        "prefer": "desktop",
        "prompt": "Teams: ",
        "executable": True,
    },
    {
        "id": "google_meet",
        "name": "Google Meet",
        "category": "Meetings",
        "icon": "🟢",
        "blurb": "Video calls",
        "action": "open",
        "url": "https://meet.google.com",
        "prompt": "Google Meet: ",
        "executable": True,
    },
    # CRM
    {
        "id": "hubspot",
        "name": "HubSpot",
        "category": "CRM",
        "icon": "🧡",
        "blurb": "CRM and pipeline",
        "action": "analysis",
        "url": "https://app.hubspot.com",
        "prompt": "HubSpot pipeline: ",
        "executable": True,
    },
    {
        "id": "salesforce",
        "name": "Salesforce",
        "category": "CRM",
        "icon": "☁",
        "blurb": "Enterprise CRM",
        "action": "analysis",
        "url": "https://login.salesforce.com",
        "prompt": "Salesforce: ",
        "executable": True,
    },
    # Automation
    {
        "id": "zapier",
        "name": "Zapier",
        "category": "Automation",
        "icon": "⚡",
        "blurb": "Automations between apps",
        "action": "open",
        "url": "https://zapier.com",
        "prompt": "Zapier: ",
        "executable": True,
    },
    {
        "id": "make",
        "name": "Make",
        "category": "Automation",
        "icon": "🔗",
        "blurb": "Scenario automations",
        "action": "open",
        "url": "https://www.make.com",
        "prompt": "Make.com: ",
        "executable": True,
    },
    {
        "id": "n8n",
        "name": "n8n",
        "category": "Automation",
        "icon": "🔁",
        "blurb": "Self-hosted workflows",
        "action": "open",
        "url": "https://n8n.io",
        "prompt": "n8n workflow: ",
        "executable": True,
    },
    # Host
    {
        "id": "browser_edge",
        "name": "Edge browser",
        "category": "Host",
        "icon": "🌐",
        "blurb": "Signed-in host Edge · remote browser",
        "action": "remote",
        "url": "https://www.bing.com",
        "desktop_app": "edge",
        "prompt": "Open in Edge: ",
        "featured": True,
        "executable": True,
    },
    {
        "id": "screen_control",
        "name": "Screen Control",
        "category": "Host",
        "icon": "🖥",
        "blurb": "Agents see and drive the host UI",
        "action": "screen",
        "prompt": "Use screen control to: ",
        "featured": True,
        "executable": True,
    },
    {
        "id": "wsl",
        "name": "WSL / Linux",
        "category": "Host",
        "icon": "🐧",
        "blurb": "Linux console for agents",
        "action": "agent",
        "agent": "wsl_native",
        "prompt": "In WSL: ",
        "executable": True,
    },
    {
        "id": "python_host",
        "name": "Python host",
        "category": "Host",
        "icon": "🐍",
        "blurb": "Host Python CLI",
        "action": "agent",
        "agent": "python",
        "prompt": "Python: ",
        "executable": True,
    },
    {
        "id": "mcp_tools",
        "name": "MCP tools",
        "category": "Host",
        "icon": "🔌",
        "blurb": "Model Context Protocol tools",
        "action": "tab",
        "tab": "mcp",
        "prompt": "Use MCP: ",
        "featured": True,
        "executable": True,
    },
    {
        "id": "working_board",
        "name": "Working board",
        "category": "Host",
        "icon": "✓",
        "blurb": "Buy · analyze · reserve ops board",
        "action": "working",
        "prompt": "",
        "featured": True,
        "executable": True,
    },
]


def catalog() -> Dict[str, Any]:
    cats: Dict[str, int] = {}
    executable_n = 0
    desktop_n = 0
    for it in INTEGRATIONS:
        c = it.get("category") or "Other"
        cats[c] = cats.get(c, 0) + 1
        if it.get("executable", True):
            executable_n += 1
        if it.get("desktop_app"):
            desktop_n += 1
    return {
        "ok": True,
        "schema": "pocket.integrations.v1",
        "count": len(INTEGRATIONS),
        "executable_count": executable_n,
        "desktop_mapped": desktop_n,
        "categories": cats,
        "featured": [i for i in INTEGRATIONS if i.get("featured")],
        "integrations": INTEGRATIONS,
        "execute": "POST /v1/integrations/{id}/execute",
        "readiness": "GET /v1/integrations/readiness",
    }


def get(integration_id: str) -> Dict[str, Any]:
    iid = (integration_id or "").strip().lower()
    for it in INTEGRATIONS:
        if it.get("id") == iid:
            return {"ok": True, "integration": it, "executable": True}
    return {"ok": False, "error": "unknown integration", "id": iid}
